### ISSUE TITLE
How To Fix Tablist Doesn't Care About Luckperms Group Weight

### ISSUE THREAD

**Issue by hazelnution** [T3CC4/SimpleTabList#1]
This Is My Issues Went There's Owner Rank And Developer The Tablist Doesn't Care About Luckperms Group Weight Only Sort The Rank
Through Alphabet

**Comment by F02K** [comment]
I'll look into that

**Comment by hazelnution** [comment]
Do I Need Also Add Weight In Prefix ?

**Comment by hazelnution** [comment]
Because Here's What I Found
/lp user/group <user|group> meta setprefix/addprefix <weight> <prefix>
It Maybe Because You Need Weight In Prefix Also

**Comment by F02K** [comment]
I use the webeditor by default. Idk if you have to set the weight on your own there.

**Comment by hazelnution** [comment]
Hmm

**Comment by hazelnution** [comment]
I Will Test It If Adding Weight Fix It

**Comment by F02K** [comment]
The Prefix should not sort your list differently. The group names could.

**Comment by hazelnution** [comment]
That's The Issues

**Comment by hazelnution** [comment]
The Owner Rank Is Lower Than Other Rank In Tablist

**Comment by F02K** [comment]
The sorting is from 0 to infinity starting from 0 as top most

**Comment by hazelnution** [comment]
Do I Need To Edit Owner Weight To 0

**Comment by F02K** [comment]
Yes if it's not on 0 you have to.

**Comment by hazelnution** [comment]
k weird

**Comment by hazelnution** [comment]
@TheYIMIR Now It's Solved

**Comment by F02K** [comment]
So it was the weight?

**Comment by hazelnution** [comment]
Yes

**Comment by F02K** [comment]
Alright

**Comment by hazelnution** [comment]
Add That Warning At Spigot Page
